### PR TITLE
Adding automated configuration and install of IPXE and ICIS

### PR DESCRIPTION
**Pull request by gtkramer**
Creating setup scripts which allow users to get up and running quickly with a PXE server running ICIS so they can bulk provision

### CODE REVIEW

**Review by rnesius — CHANGES_REQUESTED** [review]
Add "how to get started" instructions...

**Review by gtkramer — COMMENTED** [review]
Updated documentation to add a getting started section which helps users who use the git repository as their main entry point to get started quickly

**Comment by bryteise** [comment]
Oh could we get a man page?

**Comment by rnesius** [comment]
I like William's idea of a man page.  Can you check in with him tomorrow and talk about what that would look like?

**Review by rnesius — APPROVED** [review]

**Pull request merged**
